QTLTYPE1=eqtl
QTLTYPE2=sqtl
FMTYPE=dapg
RESFOLDER1=${QTLTYPE1}_${FMTYPE}
RESFOLDER2=${QTLTYPE2}_${FMTYPE}
OUTPUTFOLDER=./res_format/
GENEREFPATH=../data/gtex/gencode.v26.GRCh38.genes.gtf
TISSUELISTPATH=../data/gtex/tissues.txt
INTRONREFPATH=../data/gtex/intronref.tsv.gz
python3 res_format.py ${QTLTYPE1} ${FMTYPE} ${RESFOLDER1} ${OUTPUTFOLDER} ${GENEREFPATH} ${TISSUELISTPATH} ${INTRONREFPATH}
python3 res_format.py ${QTLTYPE2} ${FMTYPE} ${RESFOLDER2} ${OUTPUTFOLDER} ${GENEREFPATH} ${TISSUELISTPATH} ${INTRONREFPATH}
